### ISSUE TITLE
Световой эффект на картинке

### ISSUE THREAD

**Issue by scandy5** [bohodar/Crypto-Layout#2]
У тебя: 
![image](https://user-images.githubusercontent.com/41551315/57229686-5db5bf80-701f-11e9-82ff-4515ab9676f2.png)
В макете: 
![image](https://user-images.githubusercontent.com/41551315/57229717-6e663580-701f-11e9-8c96-b38ce7856987.png)

**Comment by bohodar** [comment]
Added backlighting
