### ISSUE TITLE
Задний фон из точек

### ISSUE THREAD

**Issue by scandy5** [bohodar/Crypto-Layout#3]
У тебя: 
![image](https://user-images.githubusercontent.com/41551315/57229852-b7b68500-701f-11e9-83b0-1fe3b71b6d7a.png)

В макете: 
![image](https://user-images.githubusercontent.com/41551315/57229815-aa00ff80-701f-11e9-9885-b656b4713c1f.png)

**Comment by bohodar** [comment]
Fixed.
Added point-grids
