### ISSUE TITLE
Не тот цвет фона

### ISSUE THREAD

**Issue by scandy5** [bohodar/Crypto-Layout#4]
У тебя: 
![image](https://user-images.githubusercontent.com/41551315/57229920-d583ea00-701f-11e9-907d-250e6048b599.png)
В макете: 
![image](https://user-images.githubusercontent.com/41551315/57229937-e0d71580-701f-11e9-9175-f09cde66bf69.png)

**Comment by bohodar** [comment]
Fixed a background-color
